# generated by datamodel-codegen:
#   filename:  ../packages/protocol/schema.json
#   timestamp: 2026-03-01T22:02:33+00:00

from __future__ import annotations

import datetime
import uuid
from typing import Literal, Union
from uuid import UUID

import pydantic
from pydantic import AwareDatetime, BaseModel, ConfigDict, RootModel


def createdAt_now() -> CreatedAt:
    return CreatedAt(root=datetime.datetime.now(tz=datetime.timezone.utc))

class Base(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    createdAt: AwareDatetime


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    originalId: UUID


class CreatedAt(RootModel[AwareDatetime]):
    root: AwareDatetime


class Id(RootModel[UUID]):
    root: UUID


class Chat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['chat'] = 'chat'
    name: str
    chat: str


class NameAccept(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['nameAccept'] = 'nameAccept'
    name: str


class NameError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['nameError'] = 'nameError'
    name: str
    error: str


class Ping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['ping'] = 'ping'


class Pong(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['pong'] = 'pong'
    payload: Payload


class Predict(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['predict'] = 'predict'
    after: UUID
    token: str


class ProtocolError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['protocolError'] = 'protocolError'
    error: str


class SendChat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['sendChat'] = 'sendChat'
    chat: str


class SetName(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id = pydantic.Field(default_factory=lambda: Id(root=uuid.uuid4()))
    createdAt: CreatedAt = pydantic.Field(default_factory=createdAt_now)
    type: Literal['setName'] = 'setName'
    name: str


class FromClient(
    RootModel[Union[ProtocolError, Ping, Pong, SetName, SendChat, Predict]]
):
    root: Union[ProtocolError, Ping, Pong, SetName, SendChat, Predict]


class FromServer(
    RootModel[Union[ProtocolError, Ping, Pong, NameAccept, NameError, Chat, Predict]]
):
    root: Union[ProtocolError, Ping, Pong, NameAccept, NameError, Chat, Predict]


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fromClient: FromClient
    fromServer: FromServer
