# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-01T20:34:38+00:00

from __future__ import annotations

from typing import Literal, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, RootModel


class Base(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    createdAt: AwareDatetime


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    originalId: UUID


class CreatedAt(RootModel[AwareDatetime]):
    root: AwareDatetime


class Id(RootModel[UUID]):
    root: UUID


class Chat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['chat']
    name: str
    chat: str


class NameAccept(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['nameAccept']
    name: str


class NameError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['nameError']
    name: str
    error: str


class Ping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['ping']


class Pong(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['pong']
    payload: Payload


class Predict(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['predict']
    after: UUID
    token: str


class ProtocolError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['protocolError']
    error: str


class SendChat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['sendChat']
    chat: str


class SetName(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    createdAt: CreatedAt
    type: Literal['setName']
    name: str


class FromClient(
    RootModel[Union[ProtocolError, Ping, Pong, SetName, SendChat, Predict]]
):
    root: Union[ProtocolError, Ping, Pong, SetName, SendChat, Predict]


class FromServer(
    RootModel[Union[ProtocolError, Ping, Pong, NameAccept, NameError, Chat, Predict]]
):
    root: Union[ProtocolError, Ping, Pong, NameAccept, NameError, Chat, Predict]


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fromClient: FromClient
    fromServer: FromServer
